apiVersion: apps/v1
kind: Deployment 
metadata:
  name: simple
  namespace: default 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
        - image: 'docker.io/opsmx11/restapp:simple-1.0'
          imagePullPolicy: Always 
          name: restapp 
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: prometheus
              protocol: TCP
              
---
apiVersion: v1
kind: Service
metadata:
  name: simplelb
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: canary
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: reports
  selector:
    app: simple
